name: Deploy VitePress to GitHub Pages
on:
  push:
    branches: [master]  # 或改为您的默认分支名（如main）
  workflow_dispatch:    # 支持手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码（使用v4并保留Git历史）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保lastUpdated功能正常

      # 2. 设置pnpm和Node.js环境（显式缓存）
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.1
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # 3. 配置Pages环境（升级至v4）
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      # 4. 安装依赖并构建
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build VitePress
        run: |
          pnpm docs:build
          touch docs/.vitepress/dist/.nojekyll  # 修正路径
          
        # 验证构建产物
      - name: Verify build output
        run: |
          [ -d docs/.vitepress/dist ] || exit 1
          [ -f docs/.vitepress/dist/.nojekyll ] || exit 1

      # 5. 上传产物（使用v3并明确路径）
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist  # 根据实际项目结构调整

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # 必须升级至v4
